# Generated by Django 3.2.10 on 2022-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests_management', '0002_auto_20220909_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tables',
            name='table_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
