# Generated by Django 3.2.10 on 2022-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hello_world', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'guests',
            },
        ),
    ]
