# Generated by Django 3.2.10 on 2022-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='age',
            field=models.IntegerField(),
        ),
    ]
