# Generated by Django 3.2.10 on 2022-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_alter_guests_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('guest_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Tables',
            },
        ),
        migrations.AlterModelTable(
            name='guests',
            table='Guests',
        ),
    ]
